Fix Zarr resource leaks and compilation errors - Fixed 160+ instances of unclosed zip file descriptors across 6 files:   - [FitSetupParamsAllZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/FitSetupParamsAllZarr.c:0:0-0:0) (57 fixes)   - [IntegratorZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/IntegratorZarr.c:0:0-0:0) (42 fixes)   - [IntegratorZarrOMP.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/IntegratorZarrOMP.c:0:0-0:0) (42 fixes)   - [ProcessGrainsZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/ProcessGrainsZarr.c:0:0-0:0) (10 fixes)   - [GetHKLListZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/GetHKLListZarr.c:0:0-0:0) (7 fixes)   - [read_one_frame.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/read_one_frame.c:0:0-0:0) (2 fixes) - Fixed critical double-free bugs where [free(data)](cci:1://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/PeaksFittingOMPZarrRefactor.c:291:0-300:1) was called   incorrectly after decompression into named buffers. - Fixed memory leaks in [GetHKLListZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/GetHKLListZarr.c:0:0-0:0) and [ProcessGrainsZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/ProcessGrainsZarr.c:0:0-0:0)   by adding missing [free()](cci:1://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/PeaksFittingOMPZarrRefactor.c:291:0-300:1) calls. - Fixed compilation error in [GetHKLListZarr.c](cci:7://file:///Users/hsharma/opt/MIDAS/FF_HEDM/src/GetHKLListZarr.c:0:0-0:0) by reordering includes   to ensure `stdio.h` is included before `sginfo.h`.